FROM python:3.11-slim

WORKDIR /app

COPY backend/app/requirements.txt .

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir --timeout=300 -r requirements.txt

COPY frontend ./frontend

EXPOSE 8501
CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]