services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jmlee01/aws_project_backend_260428_1
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # 데이터 파일 마운트

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: jmlee01/aws_project_frontend_260428_1
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000